version: "3.8"
services:
  wod-blog:
    container_name: wod-blog
    build:
      context: .
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4001:4001"
    environment:
      - DB_URL=mongodb://db_mongo
    depends_on:
      - wod-blog-db
  wod-blog-db:
    image: mongo
    container_name: db_mongo
    ports:
      - "27017:27017"
